In [24]:
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.decomposition import PCA

# You can add the parameter data_home to wherever to where you want to download your data
dataset = pd.read_csv('./datasets/CC.csv')
dataset = dataset.fillna(dataset.mean(numeric_only=True))
x = dataset.iloc[:,1:17].values
y = dataset.iloc[:,17].values

pca = PCA(2)
x_pca = pca.fit_transform(x)
df2 = pd.DataFrame(data=x_pca)
finaldf = pd.concat([df2,dataset[['TENURE']]],axis=1)
finaldf.head()

             0            1  TENURE
0 -4326.383979   921.566882      12
1  4118.916665 -2432.846346      12
2  1497.907641 -1997.578694      12
3  1394.548536 -1488.743453      12
4 -3743.351896   757.342657      12

In [26]:
##### K-means and PCA ########
#Applying K-means algorithm
from sklearn.cluster import KMeans
nclusters = 3 
km = KMeans(n_clusters=nclusters)
km.fit(x)

# predict the cluster for each data point
y_cluster_kmeans = km.predict(x)
from sklearn import metrics
score = metrics.silhouette_score(x, y_cluster_kmeans)
print("Silhouette_score after feature scaling:",score)

Silhouette_score after feature scaling: 0.4652332327001562

In [27]:
####scaling, K-means and PCA#########
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit on training set only.
scaler.fit(x)

# Applying feature scaling
x_scaler = scaler.transform(x)
pca = PCA(2)
x_pca = pca.fit_transform(x_scaler)
df2 = pd.DataFrame(data=x_pca)
finaldf = pd.concat([df2,dataset[['TENURE']]],axis=1)
finaldf.head()

          0         1  TENURE
0 -1.718894 -1.072936      12
1 -1.169307  2.509323      12
2  0.938425 -0.382622      12
3 -0.907505  0.045866      12
4 -1.637830 -0.684973      12

In [29]:
from sklearn.cluster import KMeans
nclusters = 3 
km = KMeans(n_clusters=nclusters)
km.fit(x_scaler)

# predict the cluster for each data point
y_cluster_kmeans = km.predict(x_scaler)
from sklearn import metrics
score = metrics.silhouette_score(x_scaler, y_cluster_kmeans)
print("Silhouette_score after feature scaling:",score)

Silhouette_score after feature scaling: 0.2673374146028887

In [65]:
#####Question-2#######
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.decomposition import PCA

dataset = pd.read_csv('./datasets/pd_speech_features.csv')
x = dataset.iloc[:,0:754].values
y = dataset.iloc[:,754].values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit on training set only.
x_scaler = scaler.fit(x)

#Applying feature scaling
x_scaler = scaler.transform(x)
pca = PCA(3)
x_pca = pca.fit_transform(x)
df2 = pd.DataFrame(data=x_pca,columns = ['PC1', 'PC2','PC3'])
finaldf = pd.concat([df2,dataset[['class']]],axis=1)
#finaldf = finaldf.astype({'PC1':'int','PC2':'int','PC3':'int'})
finaldf.head()

            PC1           PC2           PC3  class
0 -5.815816e+09  4.701391e+06 -6.210264e+05      1
1 -6.029399e+09  4.610122e+06 -4.198081e+05      1
2 -6.159184e+09  5.578720e+06 -4.115108e+05      1
3 -7.197145e+09  5.943199e+07  1.355807e+06      1
4 -6.423357e+09  8.714129e+07  1.791626e+07      1

In [66]:
#Applying SVM
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
training_set, test_set = train_test_split(dataset, test_size = 0.2, random_state = 1)
X_train = training_set.iloc[:,0:3].values
Y_train = training_set.iloc[:,3].values
X_test = test_set.iloc[:,0:3].values
Y_test = test_set.iloc[:,3].values

from sklearn.svm import SVR
classifier = SVR(kernel='linear')
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
from sklearn.metrics import r2_score
print(r2_score(Y_test,Y_pred))

0.008758465062045362

In [94]:
import numpy as np
import pandas as pd
df = pd.read_csv('./datasets/Iris.csv')
print(df.head())
X = dataset.iloc[:, 0:5].values
y = dataset.iloc[:, 5].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=2)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)
df2 = pd.DataFrame(data=X_train,columns = ['LD1', 'LD2'])
df2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

        LD1       LD2
0  1.801632 -0.377699
1  0.916307  0.220729
2 -1.399601  1.446400
3 -0.707424  0.743943
4 -1.949145  0.553152